/* GENERATED FILE — do not edit by hand.
 * Source: https://models.dev/api.json
 * Regenerate: node scripts/generate-catalog.mjs > src/ai/catalog.generated.ts
 */

import type { CatalogModel } from './catalog.js';

export const CATALOG_MODELS: CatalogModel[] = [{"id":"claude-fable-5","name":"Claude Fable 5","provider":"anthropic","costIn":10,"costOut":50,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-fable-5-1","name":"Claude Fable 5.1","provider":"anthropic","costIn":10,"costOut":50,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-haiku-4-5","name":"Claude Haiku 4.5 (latest)","provider":"anthropic","costIn":1,"costOut":5,"context":200000,"reasoning":true,"tools":true},
{"id":"claude-haiku-4-5-20251001","name":"Claude Haiku 4.5","provider":"anthropic","costIn":1,"costOut":5,"context":200000,"reasoning":true,"tools":true},
{"id":"claude-opus-4-5","name":"Claude Opus 4.5 (latest)","provider":"anthropic","costIn":5,"costOut":25,"context":200000,"reasoning":true,"tools":true},
{"id":"claude-opus-4-5-20251101","name":"Claude Opus 4.5","provider":"anthropic","costIn":5,"costOut":25,"context":200000,"reasoning":true,"tools":true},
{"id":"claude-opus-4-6","name":"Claude Opus 4.6","provider":"anthropic","costIn":5,"costOut":25,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-opus-4-7","name":"Claude Opus 4.7","provider":"anthropic","costIn":5,"costOut":25,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-opus-4-8","name":"Claude Opus 4.8","provider":"anthropic","costIn":5,"costOut":25,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-opus-5","name":"Claude Opus 5","provider":"anthropic","costIn":5,"costOut":25,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-opus-5-5","name":"Claude Opus 5.5","provider":"anthropic","costIn":4,"costOut":20,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-sonnet-4-5","name":"Claude Sonnet 4.5 (latest)","provider":"anthropic","costIn":3,"costOut":15,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-sonnet-4-5-20250929","name":"Claude Sonnet 4.5","provider":"anthropic","costIn":3,"costOut":15,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-sonnet-4-6","name":"Claude Sonnet 4.6","provider":"anthropic","costIn":3,"costOut":15,"context":1000000,"reasoning":true,"tools":true},
{"id":"claude-sonnet-5","name":"Claude Sonnet 5","provider":"anthropic","costIn":2,"costOut":10,"context":1000000,"reasoning":true,"tools":true},
{"id":"deepseek-flash","name":"DeepSeek V4.1 Flash","provider":"deepseek","costIn":0.15,"costOut":0.6,"context":1000000,"reasoning":true,"tools":true},
{"id":"deepseek-v4-flash","name":"DeepSeek V4 Flash","provider":"deepseek","costIn":0.15,"costOut":0.6,"context":1000000,"reasoning":true,"tools":true},
{"id":"deepseek-v4-flash-vision-exp","name":"DeepSeek V4 Flash Vision Exp","provider":"deepseek","costIn":0.15,"costOut":0.6,"context":1000000,"reasoning":true,"tools":true},
{"id":"deepseek-v4-pro","name":"DeepSeek V4 Pro","provider":"deepseek","costIn":0.435,"costOut":0.87,"context":1000000,"reasoning":true,"tools":true},
{"id":"deep-research-max-preview-04-2026","name":"Deep Research Max Preview (Apr-21-2026)","provider":"google","costIn":2,"costOut":12,"context":131072,"reasoning":true,"tools":true},
{"id":"deep-research-preview-04-2026","name":"Deep Research Preview (Apr-21-2026)","provider":"google","costIn":2,"costOut":12,"context":131072,"reasoning":true,"tools":true},
{"id":"gemini-2.5-computer-use-preview-10-2025","name":"Gemini 2.5 Computer Use Preview 10-2025","provider":"google","costIn":1.25,"costOut":10,"context":128000,"reasoning":true,"tools":true},
{"id":"gemini-2.5-flash","name":"Gemini 2.5 Flash","provider":"google","costIn":0.3,"costOut":2.5,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro","provider":"google","costIn":1.25,"costOut":10,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-3.1-pro-preview","name":"Gemini 3.1 Pro Preview","provider":"google","costIn":2,"costOut":12,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-3.5-flash","name":"Gemini 3.5 Flash","provider":"google","costIn":1.5,"costOut":9,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-3.5-flash-lite","name":"Gemini 3.5 Flash Lite","provider":"google","costIn":0.3,"costOut":2.5,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-3.6-flash","name":"Gemini 3.6 Flash","provider":"google","costIn":0.75,"costOut":3.75,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-flash-latest","name":"Gemini Flash Latest","provider":"google","costIn":0.75,"costOut":3.75,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-flash-lite-latest","name":"Gemini Flash-Lite Latest","provider":"google","costIn":0.3,"costOut":2.5,"context":1048576,"reasoning":true,"tools":true},
{"id":"gemini-omni-flash-preview","name":"Gemini Omni Flash Preview","provider":"google","costIn":1.5,"costOut":17.5,"context":131072,"reasoning":true},
{"id":"gemma-4-26b-a4b-it","name":"Gemma 4 26B A4B IT","provider":"google","context":262144,"reasoning":true,"tools":true},
{"id":"gemma-4-31b-it","name":"Gemma 4 31B IT","provider":"google","context":262144,"reasoning":true,"tools":true},
{"id":"lyria-3-clip-preview","name":"Lyria 3 Clip Preview","provider":"google","costIn":0,"costOut":0,"context":1048576},
{"id":"lyria-3-pro-preview","name":"Lyria 3 Pro Preview","provider":"google","costIn":0,"costOut":0,"context":1048576},
{"id":"veo-3.1-fast-generate-preview","name":"Veo 3.1 fast","provider":"google","context":480},
{"id":"veo-3.1-lite-generate-preview","name":"Veo 3.1 lite","provider":"google","context":480},
{"id":"allam-2-7b","name":"ALLaM-2-7b","provider":"groq","costIn":0,"costOut":0,"context":4096},
{"id":"canopylabs/orpheus-arabic-saudi","name":"Canopy Labs Orpheus Arabic Saudi","provider":"groq","context":4000},
{"id":"canopylabs/orpheus-v1-english","name":"Canopy Labs Orpheus V1 English","provider":"groq","context":4000},
{"id":"groq/compound","name":"Compound","provider":"groq","context":131072},
{"id":"groq/compound-mini","name":"Compound Mini","provider":"groq","context":131072},
{"id":"llama-3.1-8b-instant","name":"Llama 3.1 8B","provider":"groq","costIn":0.05,"costOut":0.08,"context":131072,"tools":true},
{"id":"llama-3.3-70b-versatile","name":"Llama 3.3 70B","provider":"groq","costIn":0.59,"costOut":0.79,"context":131072,"tools":true},
{"id":"meta-llama/llama-prompt-guard-2-22m","name":"Llama Prompt Guard 2 22M","provider":"groq","costIn":0.03,"costOut":0.03,"context":512},
{"id":"meta-llama/llama-prompt-guard-2-86m","name":"Prompt Guard 2 86M","provider":"groq","costIn":0.04,"costOut":0.04,"context":512},
{"id":"openai/gpt-oss-120b","name":"GPT OSS 120B","provider":"groq","costIn":0.15,"costOut":0.6,"context":131072,"reasoning":true,"tools":true},
{"id":"openai/gpt-oss-20b","name":"GPT OSS 20B","provider":"groq","costIn":0.075,"costOut":0.3,"context":131072,"reasoning":true,"tools":true},
{"id":"openai/gpt-oss-safeguard-20b","name":"Safety GPT OSS 20B","provider":"groq","costIn":0.075,"costOut":0.3,"context":131072,"reasoning":true,"tools":true},
{"id":"qwen/qwen3.6-27b","name":"Qwen3.6 27B","provider":"groq","costIn":0.6,"costOut":3,"context":131072,"reasoning":true,"tools":true},
{"id":"qwen/qwen3.8-27b","name":"Qwen3.8 27B","provider":"groq","costIn":0.8,"costOut":4,"context":131042,"reasoning":true,"tools":true},
{"id":"codestral-latest","name":"Codestral (latest)","provider":"mistral","costIn":0.3,"costOut":0.9,"context":256000,"tools":true},
{"id":"devstral-2512","name":"Devstral 2","provider":"mistral","costIn":0.4,"costOut":2,"context":262144,"tools":true},
{"id":"devstral-medium-latest","name":"Devstral 2 (latest)","provider":"mistral","costIn":0.4,"costOut":2,"context":262144,"tools":true},
{"id":"devstral-small-2505","name":"Devstral Small 2505","provider":"mistral","costIn":0.1,"costOut":0.3,"context":128000,"tools":true},
{"id":"magistral-medium-latest","name":"Magistral Medium (latest)","provider":"mistral","costIn":2,"costOut":5,"context":128000,"reasoning":true,"tools":true},
{"id":"ministral-8b-latest","name":"Ministral 8B (latest)","provider":"mistral","costIn":0.1,"costOut":0.1,"context":128000,"tools":true},
{"id":"mistral-embed","name":"Mistral Embed","provider":"mistral","costIn":0.1,"costOut":0,"context":8000},
{"id":"mistral-large-2411","name":"Mistral Large 2.1","provider":"mistral","costIn":2,"costOut":6,"context":131072,"tools":true},
{"id":"mistral-large-latest","name":"Mistral Large (latest)","provider":"mistral","costIn":0.5,"costOut":1.5,"context":262144,"tools":true},
{"id":"mistral-medium-2505","name":"Mistral Medium 3","provider":"mistral","costIn":0.4,"costOut":2,"context":131072,"tools":true},
{"id":"mistral-medium-2508","name":"Mistral Medium 3.1","provider":"mistral","costIn":0.4,"costOut":2,"context":262144,"tools":true},
{"id":"mistral-nemo","name":"Mistral Nemo","provider":"mistral","costIn":0.15,"costOut":0.15,"context":128000,"tools":true},
{"id":"mistral-small-2603","name":"Mistral Small 4","provider":"mistral","costIn":0.15,"costOut":0.6,"context":256000,"reasoning":true,"tools":true},
{"id":"mistral-small-latest","name":"Mistral Small (latest)","provider":"mistral","costIn":0.15,"costOut":0.6,"context":256000,"reasoning":true,"tools":true},
{"id":"open-mistral-nemo","name":"Open Mistral Nemo","provider":"mistral","costIn":0.15,"costOut":0.15,"context":128000,"tools":true},
{"id":"open-mixtral-8x22b","name":"Mixtral 8x22B","provider":"mistral","costIn":2,"costOut":6,"context":64000,"tools":true},
{"id":"pixtral-12b","name":"Pixtral 12B","provider":"mistral","costIn":0.15,"costOut":0.15,"context":128000,"tools":true},
{"id":"zai-glm-5-2","name":"GLM-5.2","provider":"mistral","costIn":1.4,"costOut":4.4,"context":1000000,"reasoning":true,"tools":true},
{"id":"gpt-3.5-turbo","name":"GPT-3.5-turbo","provider":"openai","costIn":0.5,"costOut":1.5,"context":16385},
{"id":"gpt-4","name":"GPT-4","provider":"openai","costIn":30,"costOut":60,"context":8192,"tools":true},
{"id":"gpt-4.1-nano","name":"GPT-4.1 nano","provider":"openai","costIn":0.1,"costOut":0.4,"context":1047576,"tools":true},
{"id":"gpt-4o","name":"GPT-4o","provider":"openai","costIn":2.5,"costOut":10,"context":128000,"tools":true},
{"id":"gpt-4o-2024-05-13","name":"GPT-4o (2024-05-13)","provider":"openai","costIn":5,"costOut":15,"context":128000,"tools":true},
{"id":"gpt-5-mini","name":"GPT-5 Mini","provider":"openai","costIn":0.25,"costOut":2,"context":400000,"reasoning":true,"tools":true},
{"id":"gpt-5-nano","name":"GPT-5 Nano","provider":"openai","costIn":0.05,"costOut":0.4,"context":400000,"reasoning":true,"tools":true},
{"id":"gpt-5.2-chat-latest","name":"GPT-5.2 Chat","provider":"openai","costIn":1.75,"costOut":14,"context":128000,"reasoning":true,"tools":true},
{"id":"gpt-5.2-pro","name":"GPT-5.2 Pro","provider":"openai","costIn":21,"costOut":168,"context":400000,"reasoning":true,"tools":true},
{"id":"gpt-5.3-codex","name":"GPT-5.3 Codex","provider":"openai","costIn":1.75,"costOut":14,"context":400000,"reasoning":true,"tools":true},
{"id":"gpt-5.4","name":"GPT-5.4","provider":"openai","costIn":2.5,"costOut":15,"context":1050000,"reasoning":true,"tools":true},
{"id":"gpt-5.4-nano","name":"GPT-5.4 nano","provider":"openai","costIn":0.2,"costOut":1.25,"context":400000,"reasoning":true,"tools":true},
{"id":"gpt-5.4-pro","name":"GPT-5.4 Pro","provider":"openai","costIn":30,"costOut":180,"context":1050000,"reasoning":true,"tools":true},
{"id":"gpt-5.5-pro","name":"GPT-5.5 Pro","provider":"openai","costIn":30,"costOut":180,"context":1050000,"reasoning":true,"tools":true},
{"id":"gpt-5.6","name":"GPT-5.6","provider":"openai","costIn":4,"costOut":20,"context":1050000,"reasoning":true,"tools":true},
{"id":"gpt-realtime-2.1","name":"GPT-Realtime-2.1","provider":"openai","costIn":4,"costOut":24,"context":128000,"reasoning":true,"tools":true},
{"id":"o3-mini","name":"o3-mini","provider":"openai","costIn":1.1,"costOut":4.4,"context":200000,"reasoning":true,"tools":true},
{"id":"o4-mini","name":"o4-mini","provider":"openai","costIn":1.1,"costOut":4.4,"context":200000,"reasoning":true,"tools":true},
{"id":"~moonshotai/kimi-latest","name":"Kimi Latest","provider":"openrouter","costIn":1,"costOut":9,"context":1048576,"reasoning":true,"tools":true},
{"id":"anthropic/claude-opus-4.1","name":"Claude Opus 4.1 (latest)","provider":"openrouter","costIn":15,"costOut":75,"context":200000,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-1.6","name":"Seed 1.6","provider":"openrouter","costIn":0.25,"costOut":2,"context":262144,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-1.6-flash","name":"Seed 1.6 Flash","provider":"openrouter","costIn":0.075,"costOut":0.3,"context":262144,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-2-1-turbo","name":"Seed 2.1 Turbo","provider":"openrouter","costIn":0.5,"costOut":2.5,"context":262144,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-2.0-code","name":"Seed 2.0 Code","provider":"openrouter","costIn":0.5,"costOut":3,"context":262144,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-2.0-lite","name":"Seed 2.0 Lite","provider":"openrouter","costIn":0.25,"costOut":2,"context":262144,"reasoning":true,"tools":true},
{"id":"bytedance-seed/seed-2.0-mini","name":"Seed 2.0 Mini","provider":"openrouter","costIn":0.1,"costOut":0.4,"context":262144,"reasoning":true,"tools":true},
{"id":"kwaipilot/kat-coder-pro-v2.5","name":"KAT-Coder-Pro V2.5","provider":"openrouter","costIn":0.74,"costOut":2.96,"context":262144,"tools":true},
{"id":"poolside/laguna-s-2.1","name":"Laguna S 2.1","provider":"openrouter","costIn":0.09,"costOut":0.18,"context":1048576,"reasoning":true,"tools":true},
{"id":"poolside/laguna-s-2.1:free","name":"Laguna S 2.1 (free)","provider":"openrouter","costIn":0,"costOut":0,"context":262144,"reasoning":true,"tools":true},
{"id":"poolside/laguna-xs-2.1","name":"Laguna XS 2.1","provider":"openrouter","costIn":0.06,"costOut":0.12,"context":262144,"reasoning":true,"tools":true},
{"id":"poolside/laguna-xs-2.1:free","name":"Laguna XS 2.1 (free)","provider":"openrouter","costIn":0,"costOut":0,"context":262144,"reasoning":true,"tools":true},
{"id":"prism-ml/ternary-bonsai-2-27b","name":"Ternary Bonsai 2 27B","provider":"openrouter","costIn":0.075,"costOut":0.5,"context":262144,"reasoning":true,"tools":true},
{"id":"sao10k/l3-lunaris-8b","name":"Llama 3 8B Lunaris","provider":"openrouter","costIn":0.04,"costOut":0.05,"context":8192},
{"id":"sao10k/l3.1-euryale-70b","name":"Llama 3.1 Euryale 70B v2.2","provider":"openrouter","costIn":0.85,"costOut":0.85,"context":131072,"tools":true},
{"id":"sao10k/l3.3-euryale-70b","name":"Llama 3.3 Euryale 70B","provider":"openrouter","costIn":0.65,"costOut":0.75,"context":131072},
{"id":"stealth/space-bunny-alpha","name":"Space Bunny Alpha","provider":"openrouter","costIn":0,"costOut":0,"context":1000000,"reasoning":true,"tools":true},
{"id":"grok-4.20-0309-non-reasoning","name":"Grok 4.20 (Non-Reasoning)","provider":"xai","costIn":1.25,"costOut":2.5,"context":1000000,"tools":true},
{"id":"grok-4.20-0309-reasoning","name":"Grok 4.20 (Reasoning)","provider":"xai","costIn":1.25,"costOut":2.5,"context":1000000,"reasoning":true,"tools":true},
{"id":"grok-4.20-multi-agent-0309","name":"Grok 4.20 Multi-Agent","provider":"xai","costIn":1.25,"costOut":2.5,"context":1000000,"reasoning":true},
{"id":"grok-4.3","name":"Grok 4.3","provider":"xai","costIn":1.25,"costOut":2.5,"context":1000000,"reasoning":true,"tools":true},
{"id":"grok-4.5","name":"Grok 4.5","provider":"xai","costIn":2,"costOut":6,"context":500000,"reasoning":true,"tools":true},
{"id":"grok-4.6","name":"Grok 4.6","provider":"xai","costIn":2,"costOut":6,"context":500000,"reasoning":true,"tools":true},
{"id":"grok-4.7","name":"Grok 4.7","provider":"xai","costIn":2,"costOut":6,"context":500000,"reasoning":true,"tools":true},
{"id":"grok-build-0.1","name":"Grok Build 0.1","provider":"xai","costIn":1,"costOut":2,"context":256000,"reasoning":true,"tools":true},
{"id":"grok-imagine-video","name":"Grok Imagine Video","provider":"xai","context":1024},
{"id":"grok-imagine-video-1.5","name":"Grok Imagine Video 1.5","provider":"xai","context":1024},
{"id":"glm-4.5","name":"GLM-4.5","provider":"zai","costIn":0.6,"costOut":2.2,"context":131072,"reasoning":true,"tools":true},
{"id":"glm-4.5-air","name":"GLM-4.5-Air","provider":"zai","costIn":0.2,"costOut":1.1,"context":131072,"reasoning":true,"tools":true},
{"id":"glm-4.5-flash","name":"GLM-4.5-Flash","provider":"zai","costIn":0,"costOut":0,"context":131072,"reasoning":true,"tools":true},
{"id":"glm-4.5v","name":"GLM-4.5V","provider":"zai","costIn":0.6,"costOut":1.8,"context":64000,"reasoning":true,"tools":true},
{"id":"glm-4.6","name":"GLM-4.6","provider":"zai","costIn":0.6,"costOut":2.2,"context":204800,"reasoning":true,"tools":true},
{"id":"glm-4.6v","name":"GLM-4.6V","provider":"zai","costIn":0.3,"costOut":0.9,"context":128000,"reasoning":true,"tools":true},
{"id":"glm-4.6v-flash","name":"GLM-4.6V-Flash","provider":"zai","costIn":0,"costOut":0,"context":128000,"reasoning":true,"tools":true},
{"id":"glm-4.7","name":"GLM-4.7","provider":"zai","costIn":0.6,"costOut":2.2,"context":204800,"reasoning":true,"tools":true},
{"id":"glm-4.7-flash","name":"GLM-4.7-Flash","provider":"zai","costIn":0,"costOut":0,"context":200000,"reasoning":true,"tools":true},
{"id":"glm-4.7-flashx","name":"GLM-4.7-FlashX","provider":"zai","costIn":0.07,"costOut":0.4,"context":200000,"reasoning":true,"tools":true},
{"id":"glm-5","name":"GLM-5","provider":"zai","costIn":1,"costOut":3.2,"context":204800,"reasoning":true,"tools":true},
{"id":"glm-5-turbo","name":"GLM-5-Turbo","provider":"zai","costIn":1.2,"costOut":4,"context":200000,"reasoning":true,"tools":true},
{"id":"glm-5.1","name":"GLM-5.1","provider":"zai","costIn":1.4,"costOut":4.4,"context":200000,"reasoning":true,"tools":true},
{"id":"glm-5.2","name":"GLM-5.2","provider":"zai","costIn":1.4,"costOut":4.4,"context":1000000,"reasoning":true,"tools":true},
{"id":"glm-5.3","name":"GLM-5.3","provider":"zai","costIn":1.4,"costOut":4.4,"context":1000000,"reasoning":true,"tools":true},
{"id":"glm-5.3-flash","name":"GLM-5.3-Flash","provider":"zai","costIn":0.15,"costOut":0.5,"context":1000000,"reasoning":true,"tools":true},
{"id":"glm-5.3-flashx","name":"GLM-5.3-FlashX","provider":"zai","costIn":0.37,"costOut":1.25,"context":1000000,"reasoning":true,"tools":true},
{"id":"glm-5v-turbo","name":"GLM-5V-Turbo","provider":"zai","costIn":1.2,"costOut":4,"context":200000,"reasoning":true,"tools":true}];
